name: prove
on: push

jobs:
  build:
    name: prove
    runs-on: ubuntu-latest
    timeout-minutes: 30 # job全体
    steps:
      - uses: actions/checkout@v2
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
      - run: prove -l t
